apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: k8s
  name: vault
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30080
    port: 8200
    protocol: TCP
    targetPort: 8080
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
