apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s
  name: k8s
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: k8s
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
